version: '3.5'
services:
  nginx:
    image: nginx:1.25-alpine
    read_only: true
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      -
        type: bind
        source: ${PROXY_ROOT_DIR}/containers/nginx/conf.d
        target: /etc/nginx/conf.d
        read_only: true
      -
        type: bind
        source: ${PROXY_ROOT_DIR}/containers/nginx/vhost.d
        target: /etc/nginx/vhost.d
        read_only: true
      -
        type: bind
        source: ${PROXY_ROOT_DIR}/containers/nginx/html
        target: /usr/share/nginx/html
        read_only: true
      -
        type: bind
        source: ${PROXY_ROOT_DIR}/containers/nginx/certs
        target: /etc/nginx/certs
        read_only: true
      -
        type: tmpfs
        target: /tmp
      -
        type: tmpfs
        target: /var/run
      -
        type: tmpfs
        target: /var/cache/nginx/       
    cap_drop:
      - ALL
    cap_add:
      - CAP_WAKE_ALARM
      - CAP_NET_RAW
      - CAP_NET_BIND_SERVICE
      - CAP_SETUID
      - CAP_SETGID
      - CAP_CHOWN
    networks:
      - gramc_bridge
  acme:
    image: nginxproxy/acme-companion:2.2
    restart: unless-stopped
    depends_on:
      - nginx
      - docker-gen
    volumes:
      -
        type: bind
        source: ${PROXY_ROOT_DIR}/containers/nginx/conf.d
        target: /etc/nginx/conf.d
      -
        type: bind
        source: ${PROXY_ROOT_DIR}/containers/nginx/vhost.d.INACTIF
        target: /etc/nginx/vhost.d
      -
        type: bind
        source: ${PROXY_ROOT_DIR}/containers/nginx/html
        target: /usr/share/nginx/html
      - 
        type: bind
        source: ${DOCKER_SOCK}
        target: /var/run/docker.sock
      -
        type: bind
        source: ${PROXY_ROOT_DIR}/containers/nginx/certs
        target: /etc/nginx/certs
      -
        type: bind
        source: ${PROXY_ROOT_DIR}/containers/acme/acme.sh
        target: /etc/acme.sh
    environment:
      - NGINX_PROXY_CONTAINER=proxy-nginx-1
      - NGINX_DOCKER_GEN_CONTAINER=proxy-docker-gen-1
      - DEFAULT_EMAIL=${DEFAULT_EMAIL}
    cap_drop:
      - ALL
    cap_add:
      - CAP_NET_RAW
      - CAP_CHOWN
    networks:
      - gramc_bridge
  docker-gen:
    image: jwilder/docker-gen:0.10
    read_only: true
    depends_on:
      - nginx
    restart: unless-stopped
    command: -endpoint unix:///tmp/docker.sock -notify-sighup proxy-nginx-1 -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes:
      -
        type: bind
        source: ${PROXY_ROOT_DIR}/containers/nginx/conf.d
        target: /etc/nginx/conf.d
      -
        type: bind
        source: ${PROXY_ROOT_DIR}/containers/nginx/vhost.d
        target: /etc/nginx/vhost.d
        read_only: true
      -
        type: bind
        source: ${PROXY_ROOT_DIR}/containers/nginx/certs
        target: /etc/nginx/certs
      - 
        type: bind
        source: ${DOCKER_SOCK}
        target: /tmp/docker.sock
        read_only: true
      -
        type: bind
        source: ${PROXY_ROOT_DIR}/containers/docker-gen/tmpl
        target: /etc/docker-gen/templates
        read_only: true
      -
        type: tmpfs
        target: /tmp
      -
        type: tmpfs
        target: /var/run
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=docker-gen
    cap_drop:
      - ALL
    cap_add:
      - CAP_NET_RAW
      - CAP_KILL
    networks:
      - gramc_bridge
      - default
networks:  
  gramc_bridge:
     external: true

